id = "maple-dark-pro"
name = "Maple Dark Pro"
version = "0.0.1"
schema_version = 1
authors = ["Abhilash26"]
description = "A dark AA WCAG compliant theme for Zed Editor"
repository = "https://github.com/abhilash26/maple-dark-pro.zed"